# Generated by Django 3.2.8 on 2022-02-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaLivraria', '0002_auto_20220218_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='image',
            field=models.ImageField(null=True, upload_to='imagens/', verbose_name='image'),
        ),
    ]
